# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17, 21]
        distribution: [ 'adopt' ]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Cache local Maven repository
        uses: actions/cache@main
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      - name: Chmod
        run:  chmod +x mvnw
      - name: Test with Maven
        if: ${{ matrix.java == '8' }}
        run: ./mvnw test -B -Dmaven.test.skip=false
      - name: Test with Maven
        if: ${{ matrix.java != '8' }}
        run: ./mvnw test -B -Dmaven.test.skip=false -DargLine="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.reflect.annotation=ALL-UNNAMED"
      - name: Maven Build
        run: ./mvnw install -B -V
      - name: Java Doc
        run: ./mvnw javadoc:javadoc
